In [1]:
# 토크나이징
# nltk
!pip install nltk # nltk 설치 명령어

   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 9.9 MB/s eta 0:00:00


In [2]:
import nltk # nltk를 import해서 불러옴.
nltk.download("all") # nltk에 사용될 필요한 파일들을 전체 설치하는 명령어.

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\abc.zip.
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers\averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers\av

True

In [10]:
# word_tokenize : 단어 단위로 토큰 분리, sent_tokenize : 문장 단위로 토큰 분리
from nltk.tokenize import word_tokenize

text = "사과, 배, 오렌지, 나는 3개의 사과를 구입했다."
#text = "apple, pear, orange, I bought 3 apples."
print(word_tokenize(text)) # word_tokenize로 text안에 단어를 구분하였다. word_tokenize는 영어가 기본언어이므로 영어를 사용해야한다.


['사과', ',', '배', ',', '오렌지', ',', '나는', '3개의', '사과를', '구입했다', '.']


In [5]:
import nltk
nltk.download("all", quiet=True)

True

In [11]:
from nltk.tokenize import sent_tokenize

text= """양사가 함께 진행하는 이번 캠페인은 토스 앱 이용자들이 2024년을 상징하는 3가지 키워드를 선택하면, LG유플러스가 자체 개발한 AI 기술인 ‘익시’를 활용해 다양한 캐치 캐릭터와 한 해 회고록을 생성해주는 이벤트다. 고객은 AI가 만들어 준 캐릭터와 회고록을 이미지로 저장하거나 SNS에 공유할 수 있다.

캐릭터는 토스의 오리지널 캐릭터인 ‘캐치’를 기반으로, 익시 기반의 이미지 생성 AI 기술을 적용해 완성된다. 가령 고객이 특정 키워드를 선택하면, 익시가 고객이 선택한 키워드를 분석해 ‘사랑에 빠진 에너자이저 캐치’, ‘내돈내산 멋쟁이 캐치’와 같은 캐릭터 이미지를 만들어 주는 방식이다.

앞서 양사는 AI 기술 제휴를 위한 협업을 맺고 AI를 활용한 콘텐츠 마케팅을 공동으로 추진하기로 했다. 협업의 일환으로 진행된 이번 캠페인을 통해 LG유플러스는 익시 기술을 활용한 AI 통화 에이전트 ‘익시오(ixi-O)’ 서비스도 함께 알릴 예정이다. LG유플러스는 앞으로도 더 많은 고객에게 익시 기술의 가치와 관련 서비스를 소개하고< span>, 일상 생활 속에서 AI가 제공하는 편의를 체험할 수 있도록 지원할 계획이다.

캠페인은 토스 앱 내 이벤트 채널에 접속한 고객이라면 누구나 참여할 수 있다. LG유플러스는 이번 캠페인을 시작으로 토스 고객들이 앱 내에서 익시 기술을 다양한 형태로 체험할 수 있도록 토스와 협업해나갈 예정이다.

김희진 LG유플러스 통합브랜드마케팅팀장은 “AI에 대한 고객들의 기대가 정점에 이르고 통신사의 AI 경쟁력이 중요해진 만큼, 차별화된 AI 기술을 알릴 수 있는 디지털 경험이 중요하다”며 “앞으로도 다양한 브랜드와 협업을 진행하며 많은 고객들에게 LG유플러스 AI 기술력을 선보이고, 고객 성장을 이끄는 AX 컴퍼니로 나아갈 것”이라고 말했다."""

print(sent_tokenize(text)) # 문장별로 반점으로 text안에 정보를 나열했다.

['양사가 함께 진행하는 이번 캠페인은 토스 앱 이용자들이 2024년을 상징하는 3가지 키워드를 선택하면, LG유플러스가 자체 개발한 AI 기술인 ‘익시’를 활용해 다양한 캐치 캐릭터와 한 해 회고록을 생성해주는 이벤트다.', '고객은 AI가 만들어 준 캐릭터와 회고록을 이미지로 저장하거나 SNS에 공유할 수 있다.', '캐릭터는 토스의 오리지널 캐릭터인 ‘캐치’를 기반으로, 익시 기반의 이미지 생성 AI 기술을 적용해 완성된다.', '가령 고객이 특정 키워드를 선택하면, 익시가 고객이 선택한 키워드를 분석해 ‘사랑에 빠진 에너자이저 캐치’, ‘내돈내산 멋쟁이 캐치’와 같은 캐릭터 이미지를 만들어 주는 방식이다.', '앞서 양사는 AI 기술 제휴를 위한 협업을 맺고 AI를 활용한 콘텐츠 마케팅을 공동으로 추진하기로 했다.', '협업의 일환으로 진행된 이번 캠페인을 통해 LG유플러스는 익시 기술을 활용한 AI 통화 에이전트 ‘익시오(ixi-O)’ 서비스도 함께 알릴 예정이다.', 'LG유플러스는 앞으로도 더 많은 고객에게 익시 기술의 가치와 관련 서비스를 소개하고< span>, 일상 생활 속에서 AI가 제공하는 편의를 체험할 수 있도록 지원할 계획이다.', '캠페인은 토스 앱 내 이벤트 채널에 접속한 고객이라면 누구나 참여할 수 있다.', 'LG유플러스는 이번 캠페인을 시작으로 토스 고객들이 앱 내에서 익시 기술을 다양한 형태로 체험할 수 있도록 토스와 협업해나갈 예정이다.', '김희진 LG유플러스 통합브랜드마케팅팀장은 “AI에 대한 고객들의 기대가 정점에 이르고 통신사의 AI 경쟁력이 중요해진 만큼, 차별화된 AI 기술을 알릴 수 있는 디지털 경험이 중요하다”며 “앞으로도 다양한 브랜드와 협업을 진행하며 많은 고객들에게 LG유플러스 AI 기술력을 선보이고, 고객 성장을 이끄는 AX 컴퍼니로 나아갈 것”이라고 말했다.']


In [13]:
# 레이블 인코드로 나눈다면 사과 :1 / 배 2/ 사과 1/ 오렌지 3/ 포도 4/ 배2/ 사과1 로 나누기에 중복된 값을 제외한다면
# {'사과', '오렌지', '배', '포도'}로 값이 나오게 됀다.
data = ["사과", "배", "사과", "오렌지", "포도", "배", "사과"]
print(set(data))

{'사과', '오렌지', '배', '포도'}


In [9]:
# 원핫인코딩
# 해당 레이블을 나타내는 인덱스만 1의 값을 가지고 나머지 부분은 0의 값을 가진 Binary Value로 표현하는게 LabelEncoder입니다.
#LabelEncode는 문자 그대로를 인식하지 못하기에 numpy이랑 같이 사용하기도한다.
from sklearn.preprocessing import LabelEncoder

In [14]:
import numpy as np

In [15]:
values = np.array(data)
print(values)

['사과' '배' '사과' '오렌지' '포도' '배' '사과']


In [16]:
# 레이블 인코딩
label_encoder = LabelEncoder() # 정수형태인 데이터 -> int, int 순서 -> 데이터.
# fit(...) : 기준, transform(..) : 변환
# fit_transform(..) : fit() + transform()
#integer_encoded 를 label_encoder에 fit_transform으로 values값을 변환하였다.
integer_encoded = label_encoder.fit_transform(values)

In [17]:
print(set(data)) # 세팅한 데이터 안에 값을 print로 문자를 보여주기
integer_encoded

{'사과', '오렌지', '배', '포도'}


array([1, 0, 1, 2, 3, 0, 1], dtype=int64)

In [19]:
integer_encoded = integer_encoded.reshape(-1, 1)
print(integer_encoded)
print(integer_encoded.shape)

[[1]
 [0]
 [1]
 [2]
 [3]
 [0]
 [1]]
(7, 1)


In [21]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder(sparse_output=False)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [26]:
# LabelEncoder :: invert_transform - 원핫 인코딩된 값을 가지고 다시 원래 범주로 출력.
# numpy.argmax(...) : 가장 큰 값의 인덱스 번호

inverted = label_encoder.inverse_transform([2])
print(inverted)

['오렌지']


In [29]:
inverted = label_encoder.inverse_transform([onehot_encoded[6, :].argmax()])
print(inverted)

['사과']
